CREATE TABLE schedules (
    id INTEGER PRIMARY KEY,
    post TEXT,
    link VARCHAR(255),
    twitter_username VARCHAR(255),
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posted (
    id INTEGER PRIMARY KEY,
	post_id INTEGER,
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);