CREATE TABLE posts (
    id INTEGER PRIMARY KEY,
	source_id VARCHAR(255) UNIQUE,
    content TEXT,
    link VARCHAR(255),
    twitter_username VARCHAR(255),
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posted (
    id INTEGER PRIMARY KEY,
	post_id INTEGER,
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE followers (
    id INTEGER PRIMARY KEY,
	twitter_id INTEGER UNIQUE,
	real_name VARCHAR(255),
	screen_name VARCHAR(255),
	image_url VARCHAR(255),
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);