---
- name: Deploy twitter bot script
  hosts: all
  remote_user: root
  vars:
    folder_path: /home/pi/twitter_bot
  tasks:
    - name: Clone scraper repo
      git:
        repo: https://github.com/MihaiBlebea/twitter_bot.git
        dest: "{{ folder_path }}"
        clone: yes
        update: yes

    - name: Create the virtual env
      shell:
        cmd: python3 -m venv virtualenv
        chdir: "{{ folder_path }}"
      register: out

    - debug: var=out.stdout_lines

    - name: Install the dependencies in virtualenv
      shell:
        cmd: ./virtualenv/bin/pip3 install -r requirements.txt
        chdir: "{{ folder_path }}"
      register: out

    - debug: var=out.stdout_lines

    - name: Copy env file to remote
      become: true 
      copy:
        src: ~/Projects/Python/twitter_bot/.env
        dest: "{{ folder_path }}/.env"
        owner: pi
        group: pi        
        mode: 0644

    - name: Creating an executable file
      copy:
        dest: "/home/pi/.local/bin/twitter_bot"
        content: |
            #!/bin/bash
            cd {{ folder_path }} && ./publish.sh "${@}"

    - name: Create a new file with permissions
      file:
        path: "/home/pi/.local/bin/twitter_bot"
        state: touch
        mode: 0777
        owner: pi