---
- name: Deploy the zoopla scraper
  hosts: all
  vars:
    folder_path: /home/pi/twitter_bot
  tasks:
    - name: Clone scraper repo
      git:
        repo: https://github.com/MihaiBlebea/twitter_bot.git
        dest: "{{ folder_path }}"
        clone: yes
        update: yes

    - name: Install the software
      shell:
        cmd: sqlite3 store.db < ./init.sql
        chdir: "{{ folder_path }}"
      register: out

    - debug: var=out.stdout_lines

    - name: Create publish cron job
      cron:
        name: "twitter bot crons"
        minute: "0"
        hour: "9,11,13,17,19"
        job: "cd ${HOME}/twitter_bot && ./execute.sh >> ${HOME}/twitter_bot.log 2>&1"

    - name: Create followers cron job
      cron:
        name: "twitter bot crons"
        minute: "0"
        hour: "20"
        job: "cd ${HOME}/twitter_bot && ./execute.sh followers >> ${HOME}/twitter_bot_logs.log 2>&1"

    - name: Create retweets cron job
      cron:
        name: "twitter bot crons"
        minute: "0"
        hour: "10,14,15"
        job: "cd ${HOME}/twitter_bot && ./retweet.sh retweet >> ${HOME}/twitter_bot_logs.log 2>&1"

    - name: Create report cron job
      cron:
        name: "twitter bot crons"
        minute: "0"
        hour: "21"
        job: "cd ${HOME}/twitter_bot && ./execute.sh report >> ${HOME}/twitter_bot_logs.log 2>&1"

    - name: Create the virtual env
      shell:
        cmd: python3 -m venv virtualenv
        chdir: "{{ folder_path }}"
      register: out

    - debug: var=out.stdout_lines

    - name: Install the dependencies in virtualenv
      shell:
        cmd: ./virtualenv/bin/pip3 install -r requirements.txt
        chdir: "{{ folder_path }}"
      register: out

    - debug: var=out.stdout_lines

    - name: Copy env file to remote
      become: true 
      copy:
        src: ~/Projects/Python/twitter_bot/.env
        dest: "{{ folder_path }}/.env"
        owner: pi
        group: pi        
        mode: 0644