---
- name: Remove the jobs scraper
  hosts: all
  vars:
    folder_path: /home/pi/twitter_bot
  tasks:
    - name: Backup the database
      shell:
        cmd: cp ./store.db ./../twitter_bot_store.db
        chdir: "{{ folder_path }}"
      register: out

    - name: Removes the folder
      shell:
        cmd: "rm -rf {{ folder_path }}"
      register: out

    - debug: var=out.stdout_lines

    - name: Removing the file from bin
      file:
        path: "/home/pi/.local/bin/twitter_bot"
        state: absent